name: PR preview

on:
  pull_request:
    types: [opened, reopened]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Create PR build directory
        run: mkdir pr-preview/pr-${{ github.event.pull_request.number }}
      - name: Build PR artifacts
        run: |
          cargo install --git https://github.com/montyly/mdBook.git mdbook || true
          mdbook build -d pr-preview/pr-${{ github.event.pull_request.number }}
      - name: Copy PR build to new directory
        run: rsync -av --exclude=pr-preview/* pr-preview/pr-${{ github.event.pull_request.number }} pr-preview/
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Build master branch
        run: |
          cargo install --git https://github.com/montyly/mdBook.git mdbook || true
          mdbook build
      - name: Include PR preview in master build
        run: mv pr-preview/pr-${{ github.event.pull_request.number }} book/pr-${{ github.event.pull_request.number }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: book
  cleanup:
    needs: checkout
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.pull_request.state == 'closed'
    steps:
      - name: Delete PR preview directory
        run: rm -rf pr-preview/pr-${{ github.event.pull_request.number }}
