name: PR preview

on:
  pull_request:
    types: [opened, reopened]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: pr-preview

      - name: Create PR build directory
        run: mkdir pr-preview/pr-${{ github.event.number }}

      - name: Loop through open pull requests
        run: |
          for pull_request in $(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=master" \
            | jq -r ".[] | select(.number != ${{ github.event.number }}) | .number"); do
              echo "Building PR #$pull_request"
              cargo install --git https://github.com/montyly/mdBook.git mdbook || true
              mdbook build ./pr-preview -d pr-preview/pr-$pull_request
          done

      - name: Build PR artifacts for current pull request
        run: |
          cargo install --git https://github.com/montyly/mdBook.git mdbook || true
          mdbook build ./pr-preview -d pr-preview/pr-${{ github.event.pull_request.number }}

      - name: Copy PR builds to new directory
        run: |
          rsync -av --exclude=pr-preview/* pr-preview/ pr-preview-all/
          rsync -av --exclude=pr-preview-all/* pr-preview/pr-${{ github.event.pull_request.number }} pr-preview-all/

      - name: Cache PR build artifacts
        uses: actions/cache@v3
        with:
          path: pr-preview-all/
          key: pr-preview-all

  checkout-master:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Restore PR build artifacts from cache
        uses: actions/cache@v3
        with:
          path: pr-preview-all/
          key: pr-preview-all

      - name: Build master branch
        run: |
          cargo install --git https://github.com/montyly/mdBook.git mdbook || true
          mdbook build

      - name: Include PR previews in master build
        run: |
          rsync -av --exclude=pr-preview-all/* pr-preview-all/ book/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: checkout-master
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
